[tools]
cosign                                 = "3.1.2"
go                                     = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.6.0"
golangci-lint                          = "latest"
goreleaser                             = "latest"
just                                   = "latest"
"pipx:pre-commit"                      = "4.6.0"

[settings]
activate_aggressive = true
env_cache           = true
exec_auto_install   = true
github_attestations = true
lockfile            = true
pin                 = true
slsa                = true

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true
