[tools]
cosign                                 = "3.1.2"
go                                     = "1.26.5"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.6.0"
golangci-lint                          = "2.12.2"
goreleaser                             = "2.17.0"
just                                   = "1.56.0"
"pipx:pre-commit"                      = "4.6.0"

[settings]
activate_aggressive = true
env_cache           = true
exec_auto_install   = true
github_attestations = true
lockfile            = true
pin                 = true
slsa                = true

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true
